### PR TITLE
Change fastapath attr name to path

### PR DESCRIPTION
**Pull request by simonepignotti**

### CODE REVIEW

**Comment by karel-brinda** [comment]
@simonepignotti Great! Could you just add unit tests, please?

**Comment by karel-brinda** [comment]
Also, the documentation needs to be updated accordingly: https://prophyle.github.io/formats.html#id2 (adding `path`, marking `fastapath` as deprec,).

**Comment by simonepignotti** [comment]
Right, should I do it in this branch or in ``docs``?

**Comment by karel-brinda** [comment]
Great, it looks good. Could you please just add the fastapath parameter to the documentation and mark it as deprecated? It's important to be keep backward compatibility both in the code and in the documentation. Thanks.

**Comment by simonepignotti** [comment]
I added it as a comment to the path attribute specification, is that ok?

**Pull request merged**
